package com.poly.entity;
// Generated Jul 26, 2019 9:48:09 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdminModuleInRole generated by hbm2java
 */
@Entity
@Table(name = "AdminModuleInRole", schema = "dbo", catalog = "Learn_code_db")
public class AdminModuleInRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5516083578137681736L;
	private Integer id;
	private AdminModule adminModule;
	private AdminRole adminRole;

	public AdminModuleInRole() {
	}

	public AdminModuleInRole(AdminModule adminModule, AdminRole adminRole) {
		this.adminModule = adminModule;
		this.adminRole = adminRole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AdminModuleID")
	public AdminModule getAdminModule() {
		return this.adminModule;
	}

	public void setAdminModule(AdminModule adminModule) {
		this.adminModule = adminModule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AdminRoleID")
	public AdminRole getAdminRole() {
		return this.adminRole;
	}

	public void setAdminRole(AdminRole adminRole) {
		this.adminRole = adminRole;
	}
}
