package com.poly.entity;
// Generated Jul 22, 2019 3:26:12 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "Course", schema = "dbo", catalog = "Learn_code_db")
public class Course implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private String description;
	private String code;
	private boolean isActive;
	private boolean isDeleted;
	private Set<Syllabus> syllabuses = new HashSet<Syllabus>(0);

	public Course() {
	}

	public Course(String name, String description, String code, boolean isActive, boolean isDeleted) {
		this.name = name;
		this.description = description;
		this.code = code;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
	}

	public Course(String name, String description, String code, boolean isActive, boolean isDeleted,
			Set<Syllabus> syllabuses) {
		this.name = name;
		this.description = description;
		this.code = code;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
		this.syllabuses = syllabuses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "code", nullable = false, length = 32)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Syllabus> getSyllabuses() {
		return this.syllabuses;
	}

	public void setSyllabuses(Set<Syllabus> syllabuses) {
		this.syllabuses = syllabuses;
	}

}
