package com.poly.entity;
// Generated Jul 24, 2019 11:22:08 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.OrderColumn;
import javax.persistence.Table;

import org.hibernate.annotations.Where;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "Course", schema = "dbo", catalog = "Learn_code_db")
public class Course implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private String content;
	private String description;
	private String timeToComplete;
	private String prerequisite;
	private String nameAscii;
	private String code;
	private boolean isActive;
	private boolean isDeleted;
	private Language language;
	private Set<Syllabus> syllabuses;
	private Set<Record> records = new HashSet<Record>(0);

	public Course() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "content", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}
	
	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "timeToComplete", nullable = false)
	public String getTimeToComplete() {
		return timeToComplete;
	}

	public void setTimeToComplete(String timeToComplete) {
		this.timeToComplete = timeToComplete;
	}

	@Column(name = "prerequisite", nullable = false)
	public String getPrerequisite() {
		return prerequisite;
	}

	public void setPrerequisite(String prerequisite) {
		this.prerequisite = prerequisite;
	}

	@Column(name = "nameAscii", nullable = false)
	public String getNameAscii() {
		return nameAscii;
	}

	public void setNameAscii(String nameAscii) {
		this.nameAscii = nameAscii;
	}

	public void setDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "code", nullable = false, length = 32)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Language_id", nullable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Record> getRecords() {
		return this.records;
	}

	public void setRecords(Set<Record> records) {
		this.records = records;
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH, mappedBy = "course")
	@Column(nullable = false, updatable = false, insertable = false)
	@OrderBy("orderDisplay ASC")
	@Where(clause= "isDeleted = 0")
	public Set<Syllabus> getSyllabuses() {
		return this.syllabuses;
	}

	public void setSyllabuses(Set<Syllabus> syllabuses) {
		this.syllabuses = syllabuses;
	}

}
