package com.poly.entity;
// Generated Jul 24, 2019 11:22:08 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LessionType generated by hbm2java
 */
@Entity
@Table(name = "Language", schema = "dbo", catalog = "Learn_code_db")
public class Language implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6046208921794533329L;
	private Integer id;
	private String name;
	private boolean isDeleted;
	private Set<Course> courses = new HashSet<Course>(0);

	public Language() {
	}

	public Language(String name, boolean isDeleted) {
		this.name = name;
		this.isDeleted = isDeleted;
	}

	public Language(String name, boolean isActive, boolean isDeleted, Set<Course> courses) {
		this.name = name;
		this.isDeleted = isDeleted;
		this.courses = courses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

}
