package com.poly.entity;
// Generated Jul 22, 2019 3:26:12 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lession generated by hbm2java
 */
@Entity
@Table(name = "Lession", schema = "dbo", catalog = "Learn_code_db")
public class Lession implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private LessionType lessionType;
	private Syllabus syllabus;
	private String name;
	private int order;
	private String description;
	private String content;
	private String code;
	private boolean isActive;
	private boolean isDeleted;
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<Record> records = new HashSet<Record>(0);

	public Lession() {
	}

	public Lession(LessionType lessionType, Syllabus syllabus, String name, int order, String description,
			String content, String code, boolean isActive, boolean isDeleted) {
		this.lessionType = lessionType;
		this.syllabus = syllabus;
		this.name = name;
		this.order = order;
		this.description = description;
		this.content = content;
		this.code = code;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
	}

	public Lession(LessionType lessionType, Syllabus syllabus, String name, int order, String description,
			String content, String code, boolean isActive, boolean isDeleted, Set<Question> questions,
			Set<Record> records) {
		this.lessionType = lessionType;
		this.syllabus = syllabus;
		this.name = name;
		this.order = order;
		this.description = description;
		this.content = content;
		this.code = code;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
		this.questions = questions;
		this.records = records;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LessionType_id", nullable = false)
	public LessionType getLessionType() {
		return this.lessionType;
	}

	public void setLessionType(LessionType lessionType) {
		this.lessionType = lessionType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Syllabus_id", nullable = false)
	public Syllabus getSyllabus() {
		return this.syllabus;
	}

	public void setSyllabus(Syllabus syllabus) {
		this.syllabus = syllabus;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "content", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "code", nullable = false, length = 32)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lession")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lession")
	public Set<Record> getRecords() {
		return this.records;
	}

	public void setRecords(Set<Record> records) {
		this.records = records;
	}

}
