package com.poly.entity;
// Generated Jul 22, 2019 3:26:12 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LessionType generated by hbm2java
 */
@Entity
@Table(name = "LessionType", schema = "dbo", catalog = "Learn_code_db")
public class LessionType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private boolean isActive;
	private boolean isDeleted;
	private Set<Lession> lessions = new HashSet<Lession>(0);

	public LessionType() {
	}

	public LessionType(String name, boolean isActive, boolean isDeleted) {
		this.name = name;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
	}

	public LessionType(String name, boolean isActive, boolean isDeleted, Set<Lession> lessions) {
		this.name = name;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
		this.lessions = lessions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lessionType")
	public Set<Lession> getLessions() {
		return this.lessions;
	}

	public void setLessions(Set<Lession> lessions) {
		this.lessions = lessions;
	}

}
