package com.poly.entity;
// Generated Jul 24, 2019 11:22:08 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LessionType generated by hbm2java
 */
@Entity
@Table(name = "LessionType", schema = "dbo", catalog = "Learn_code_db")
public class LessionType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6046208921794533329L;
	private Integer id;
	private String name;
	private String code;
	private boolean isActive;
	private boolean isDeleted;
	private Set<Lession> lessions = new HashSet<Lession>(0);

	public LessionType() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "code", nullable = false) 
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lessionType")
	public Set<Lession> getLessions() {
		return this.lessions;
	}

	public void setLessions(Set<Lession> lessions) {
		this.lessions = lessions;
	}

}
