package com.poly.entity;
// Generated Jul 24, 2019 11:22:08 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "Member", schema = "dbo", catalog = "Learn_code_db")
public class Member implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8046818703889743539L;
	private Integer id;
	private User user;
	private String name;
	private String email;
	private String address;
	private String profileimage;
	private boolean isActive;
	private boolean isDeleted;
	private Timestamp createdDate;
	private Timestamp trailExpiredDate;
	private Timestamp proExpiredDate;
	private Set<Record> records = new HashSet<Record>(0);

	public Member() {
	}

	public Member( User user, String name, String email, String address, String profileimage,
			boolean isActive, boolean isDeleted, Timestamp createdDate, Timestamp trailExpiredDate,
			Timestamp proExpiredDate) {
		this.user = user;
		this.name = name;
		this.email = email;
		this.address = address;
		this.profileimage = profileimage;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
		this.createdDate = createdDate;
		this.trailExpiredDate = trailExpiredDate;
		this.proExpiredDate = proExpiredDate;
	}

	public Member(User user, String name, String email, String address, String profileimage, boolean isActive,
			boolean isDeleted, Set<Record> records) {
		this.user = user;
		this.name = name;
		this.email = email;
		this.address = address;
		this.profileimage = profileimage;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
		this.records = records;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 512)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "profileimage", nullable = false)
	public String getProfileimage() {
		return this.profileimage;
	}

	public void setProfileimage(String profileimage) {
		this.profileimage = profileimage;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "createdDate", insertable = false, updatable = false)
	public Timestamp getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Timestamp createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "trailExpiredDate")
	public Timestamp getTrailExpiredDate() {
		return trailExpiredDate;
	}

	public void setTrailExpiredDate(Timestamp trailExpiredDate) {
		this.trailExpiredDate = trailExpiredDate;
	}

	@Column(name = "proExpiredDat")
	public Timestamp getProExpiredDate() {
		return proExpiredDate;
	}

	public void setProExpiredDate(Timestamp proExpiredDate) {
		this.proExpiredDate = proExpiredDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Record> getRecords() {
		return this.records;
	}

	public void setRecords(Set<Record> records) {
		this.records = records;
	}

}
