package com.poly.entity;
// Generated Jul 24, 2019 11:22:08 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.hibernate.annotations.Where;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "Question", schema = "dbo", catalog = "Learn_code_db")
public class Question implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4965841764265309538L;
	private Integer id;
	private Lession lession;
	private String title;
	private String content;
	private Integer orderDisplay;
	private String description;
	private String fileName;
	private String defaultCode;
	private String code;
	private boolean isActive;
	private boolean isDeleted;
	private Set<QuestionInstruction> instructions = new HashSet<QuestionInstruction>(0);
	private Set<Quiz> quizs = new HashSet<Quiz>(0);
	private Set<RecordQuestion> recordQuestions = new HashSet<RecordQuestion>(0);

	public Question() {
	}

	@Id 
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Lession_id")
	public Lession getLession() {
		return this.lession;
	}

	public void setLession(Lession lession) {
		this.lession = lession;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent (String content) {
		this.content = content;
	}
	
	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle (String title) {
		this.title = title;
	}

	@Column(name = "orderDisplay")
	public Integer getOrderDisplay() {
		return this.orderDisplay;
	}

	public void setOrderDisplay(Integer orderDisplay) {
		this.orderDisplay = orderDisplay;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription (String description) {
		this.description = description;
	}

	@Column(name = "fileName")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName (String fileName) {
		this.fileName = fileName;
	}
	
	@Column(name = "default_code")
	public String getDefaultCode() {
		return this.defaultCode;
	}

	public void setDefaultCode (String defaultCode) {
		this.defaultCode = defaultCode;
	}

	@Column(name = "code", length = 32)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "isActive")
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isDeleted")
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "question")
	@OrderBy("orderDisplay ASC")
	@Where(clause= "isDeleted = 0")
	public Set<QuestionInstruction> getInstructions() {
		return this.instructions;
	}

	public void setInstructions(Set<QuestionInstruction> instruction) {
		this.instructions = instruction;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	@Where(clause= "isDeleted = 0")
	public Set<Quiz> getQuizs() {
		return this.quizs;
	}

	public void setQuizs(Set<Quiz> quizs) {
		this.quizs = quizs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<RecordQuestion> getRecordQuestions() {
		return this.recordQuestions;
	}

	public void setRecordQuestions(Set<RecordQuestion> recordQuestions) {
		this.recordQuestions = recordQuestions;
	}
}
