package com.poly.entity;
// Generated Jul 24, 2019 11:22:08 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "Question_Instruction", schema = "dbo", catalog = "Learn_code_db")
public class QuestionInstruction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4965841764265309538L;
	private Integer id;
	private String content;
	private String hint;
	private String result;
	private String requiredCode;
	private Integer orderDisplay;
	private String code;
	private boolean isActive;
	private boolean isDeleted;
	private Question question;

	public QuestionInstruction() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent (String content) {
		this.content = content;
	}
	
	@Column(name = "hint")
	public String getHint() {
		return this.hint;
	}

	public void setHint (String hint) {
		this.hint = hint;
	}

	@Column(name = "result")
	public String getResult() {
		return this.result;
	}

	public void setResult (String result) {
		this.result = result;
	}
	
	@Column(name = "requiredCode")
	public String getRequiredCode() {
		return this.requiredCode;
	}

	public void setRequiredCode (String requiredCode) {
		this.requiredCode = requiredCode;
	}

	@Column(name = "orderDisplay")
	public Integer getOrderDisplay() {
		return this.orderDisplay;
	}

	public void setOrderDisplay(Integer orderDisplay) {
		this.orderDisplay = orderDisplay;
	}
	
	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode (String code) {
		this.code = code;
	}

	@Column(name = "isActive")
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isDeleted")
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Question_id")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}
}
