package com.poly.entity;
// Generated Jul 22, 2019 3:26:12 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Quiz generated by hbm2java
 */
@Entity
@Table(name = "Quiz", schema = "dbo", catalog = "Learn_code_db")
public class Quiz implements java.io.Serializable {

	private Integer id;
	private Question question;
	private Serializable answer;
	private boolean isActive;
	private boolean isDeleted;

	public Quiz() {
	}

	public Quiz(Question question, boolean isActive, boolean isDeleted) {
		this.question = question;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
	}

	public Quiz(Question question, Serializable answer, boolean isActive, boolean isDeleted) {
		this.question = question;
		this.answer = answer;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Question_id", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "answer")
	public Serializable getAnswer() {
		return this.answer;
	}

	public void setAnswer(Serializable answer) {
		this.answer = answer;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
