package com.poly.entity;
// Generated Jul 22, 2019 3:26:12 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RecordQuestion generated by hbm2java
 */
@Entity
@Table(name = "Record_Question", schema = "dbo", catalog = "Learn_code_db")
public class RecordQuestion implements java.io.Serializable {

	private Integer id;
	private Question question;
	private Record record;
	private Serializable tempCode;
	private int resultQuiz;
	private boolean isActive;
	private boolean isDeleted;

	public RecordQuestion() {
	}

	public RecordQuestion(Question question, Record record, Serializable tempCode, int resultQuiz, boolean isActive,
			boolean isDeleted) {
		this.question = question;
		this.record = record;
		this.tempCode = tempCode;
		this.resultQuiz = resultQuiz;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Question_id", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Record_id", nullable = false)
	public Record getRecord() {
		return this.record;
	}

	public void setRecord(Record record) {
		this.record = record;
	}

	@Column(name = "temp_code", nullable = false)
	public Serializable getTempCode() {
		return this.tempCode;
	}

	public void setTempCode(Serializable tempCode) {
		this.tempCode = tempCode;
	}

	@Column(name = "result_quiz", nullable = false)
	public int getResultQuiz() {
		return this.resultQuiz;
	}

	public void setResultQuiz(int resultQuiz) {
		this.resultQuiz = resultQuiz;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
