package com.poly.entity;
// Generated Jul 22, 2019 3:26:12 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Record generated by hbm2java
 */
@Entity
@Table(name = "Record", schema = "dbo", catalog = "Learn_code_db")
public class Record implements java.io.Serializable {

	private Integer id;
	private Lession lession;
	private Member member;
	private boolean correct;
	private boolean isActive;
	private boolean isDeleted;
	private Set<RecordQuestion> recordQuestions = new HashSet<RecordQuestion>(0);

	public Record() {
	}

	public Record(Lession lession, Member member, boolean correct, boolean isActive, boolean isDeleted) {
		this.lession = lession;
		this.member = member;
		this.correct = correct;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
	}

	public Record(Lession lession, Member member, boolean correct, boolean isActive, boolean isDeleted,
			Set<RecordQuestion> recordQuestions) {
		this.lession = lession;
		this.member = member;
		this.correct = correct;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
		this.recordQuestions = recordQuestions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Lession_id", nullable = false)
	public Lession getLession() {
		return this.lession;
	}

	public void setLession(Lession lession) {
		this.lession = lession;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Customer_id", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "correct", nullable = false)
	public boolean isCorrect() {
		return this.correct;
	}

	public void setCorrect(boolean correct) {
		this.correct = correct;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "record")
	public Set<RecordQuestion> getRecordQuestions() {
		return this.recordQuestions;
	}

	public void setRecordQuestions(Set<RecordQuestion> recordQuestions) {
		this.recordQuestions = recordQuestions;
	}

}
