package com.poly.entity;
// Generated Jul 24, 2019 11:22:08 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "Tag", schema = "dbo", catalog = "Learn_code_db")
public class Tag implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1031183169605251472L;
	private Integer id;
	private String title;
	private String body;
	private Date createdAt;
	private Date updatedAt;
	private Set<TopicTag> topicTags = new HashSet<TopicTag>(0);

	public Tag() {
	}

	public Tag(String title, String body, Date createdAt, Date updatedAt) {
		this.title = title;
		this.body = body;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Tag(String title, String body, Date createdAt, Date updatedAt, Set<TopicTag> topicTags) {
		this.title = title;
		this.body = body;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.topicTags = topicTags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "body", nullable = false)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
	public Set<TopicTag> getTopicTags() {
		return this.topicTags;
	}

	public void setTopicTags(Set<TopicTag> topicTags) {
		this.topicTags = topicTags;
	}

}
