package com.poly.entity;
// Generated Jul 22, 2019 3:26:12 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "Tag", schema = "dbo", catalog = "Learn_code_db")
public class Tag implements java.io.Serializable {

	private Integer id;
	private Serializable title;
	private Serializable body;
	private Date createdAt;
	private Date updatedAt;
	private Set<TopicTag> topicTags = new HashSet<TopicTag>(0);

	public Tag() {
	}

	public Tag(Serializable title, Serializable body, Date createdAt, Date updatedAt) {
		this.title = title;
		this.body = body;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Tag(Serializable title, Serializable body, Date createdAt, Date updatedAt, Set<TopicTag> topicTags) {
		this.title = title;
		this.body = body;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.topicTags = topicTags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public Serializable getTitle() {
		return this.title;
	}

	public void setTitle(Serializable title) {
		this.title = title;
	}

	@Column(name = "body", nullable = false)
	public Serializable getBody() {
		return this.body;
	}

	public void setBody(Serializable body) {
		this.body = body;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
	public Set<TopicTag> getTopicTags() {
		return this.topicTags;
	}

	public void setTopicTags(Set<TopicTag> topicTags) {
		this.topicTags = topicTags;
	}

}
