package com.poly.entity;
// Generated Jul 22, 2019 3:26:12 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Topic generated by hbm2java
 */
@Entity
@Table(name = "Topic", schema = "dbo", catalog = "Learn_code_db")
public class Topic implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private User user;
	private String title;
	private String body;
	private Date createdAt;
	private Date updatedAt;
	private Set<Post> posts = new HashSet<Post>(0);
	private Set<TopicTag> topicTags = new HashSet<TopicTag>(0);

	public Topic() {
	}

	public Topic(User user, String title, String body, Date createdAt, Date updatedAt) {
		this.user = user;
		this.title = title;
		this.body = body;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Topic(User user, String title, String body, Date createdAt, Date updatedAt, Set<Post> posts,
			Set<TopicTag> topicTags) {
		this.user = user;
		this.title = title;
		this.body = body;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.posts = posts;
		this.topicTags = topicTags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "body", nullable = false)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topic")
	public Set<Post> getPosts() {
		return this.posts;
	}

	public void setPosts(Set<Post> posts) {
		this.posts = posts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topic")
	public Set<TopicTag> getTopicTags() {
		return this.topicTags;
	}

	public void setTopicTags(Set<TopicTag> topicTags) {
		this.topicTags = topicTags;
	}

}
