package com.poly.entity;
// Generated Jul 22, 2019 3:26:12 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WebsiteConfig generated by hbm2java
 */
@Entity
@Table(name = "Website_Config", schema = "dbo", catalog = "Learn_code_db")
public class WebsiteConfig implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String lang;
	private String name;
	private String email;
	private String openHour;
	private String mobile;
	private String copyRight;
	private String hotline;
	private String link;
	private String headScript;
	private String startBodyScript;
	private String endBodyScript;
	private String googleMap;
	private String address;
	private String facebookLink;
	private String googleLink;
	private String twitterLink;
	private String youtubeLink;
	private Boolean isDeleted;

	public WebsiteConfig() {
	}

	public WebsiteConfig(String lang) {
		this.lang = lang;
	}

	public WebsiteConfig(String lang, String name, String email, String openHour, String mobile,
			String copyRight, String hotline, String link, String headScript, String startBodyScript,
			String endBodyScript, String googleMap, String address, String facebookLink,
			String googleLink, String twitterLink, String youtubeLink, Boolean isDeleted) {
		this.lang = lang;
		this.name = name;
		this.email = email;
		this.openHour = openHour;
		this.mobile = mobile;
		this.copyRight = copyRight;
		this.hotline = hotline;
		this.link = link;
		this.headScript = headScript;
		this.startBodyScript = startBodyScript;
		this.endBodyScript = endBodyScript;
		this.googleMap = googleMap;
		this.address = address;
		this.facebookLink = facebookLink;
		this.googleLink = googleLink;
		this.twitterLink = twitterLink;
		this.youtubeLink = youtubeLink;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "lang", unique = true, nullable = false, length = 50)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "openHour")
	public String getOpenHour() {
		return this.openHour;
	}

	public void setOpenHour(String openHour) {
		this.openHour = openHour;
	}

	@Column(name = "mobile", length = 100)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "copyRight")
	public String getCopyRight() {
		return this.copyRight;
	}

	public void setCopyRight(String copyRight) {
		this.copyRight = copyRight;
	}

	@Column(name = "hotline", length = 100)
	public String getHotline() {
		return this.hotline;
	}

	public void setHotline(String hotline) {
		this.hotline = hotline;
	}

	@Column(name = "link", length = 200)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "headScript")
	public String getHeadScript() {
		return this.headScript;
	}

	public void setHeadScript(String headScript) {
		this.headScript = headScript;
	}

	@Column(name = "startBodyScript")
	public String getStartBodyScript() {
		return this.startBodyScript;
	}

	public void setStartBodyScript(String startBodyScript) {
		this.startBodyScript = startBodyScript;
	}

	@Column(name = "endBodyScript")
	public String getEndBodyScript() {
		return this.endBodyScript;
	}

	public void setEndBodyScript(String endBodyScript) {
		this.endBodyScript = endBodyScript;
	}

	@Column(name = "googleMap")
	public String getGoogleMap() {
		return this.googleMap;
	}

	public void setGoogleMap(String googleMap) {
		this.googleMap = googleMap;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "facebookLink")
	public String getFacebookLink() {
		return this.facebookLink;
	}

	public void setFacebookLink(String facebookLink) {
		this.facebookLink = facebookLink;
	}

	@Column(name = "googleLink")
	public String getGoogleLink() {
		return this.googleLink;
	}

	public void setGoogleLink(String googleLink) {
		this.googleLink = googleLink;
	}

	@Column(name = "twitterLink")
	public String getTwitterLink() {
		return this.twitterLink;
	}

	public void setTwitterLink(String twitterLink) {
		this.twitterLink = twitterLink;
	}

	@Column(name = "youtubeLink")
	public String getYoutubeLink() {
		return this.youtubeLink;
	}

	public void setYoutubeLink(String youtubeLink) {
		this.youtubeLink = youtubeLink;
	}

	@Column(name = "isDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
