package com.poly.entity;
// Generated Jul 24, 2019 11:22:08 PM by Hibernate Tools 5.0.6.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WebsiteConfig generated by hbm2java
 */
@Entity
@Table(name = "Website_Config", schema = "dbo", catalog = "Learn_code_db")
public class WebsiteConfig implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4129530199259863401L;
	private String lang;
	private Serializable name;
	private Serializable email;
	private Serializable openHour;
	private String mobile;
	private Serializable copyRight;
	private String hotline;
	private String link;
	private Serializable headScript;
	private Serializable startBodyScript;
	private Serializable endBodyScript;
	private Serializable googleMap;
	private Serializable address;
	private Serializable facebookLink;
	private Serializable googleLink;
	private Serializable twitterLink;
	private Serializable youtubeLink;
	private Boolean isDeleted;

	public WebsiteConfig() {
	}

	public WebsiteConfig(String lang) {
		this.lang = lang;
	}

	public WebsiteConfig(String lang, Serializable name, Serializable email, Serializable openHour, String mobile,
			Serializable copyRight, String hotline, String link, Serializable headScript, Serializable startBodyScript,
			Serializable endBodyScript, Serializable googleMap, Serializable address, Serializable facebookLink,
			Serializable googleLink, Serializable twitterLink, Serializable youtubeLink, Boolean isDeleted) {
		this.lang = lang;
		this.name = name;
		this.email = email;
		this.openHour = openHour;
		this.mobile = mobile;
		this.copyRight = copyRight;
		this.hotline = hotline;
		this.link = link;
		this.headScript = headScript;
		this.startBodyScript = startBodyScript;
		this.endBodyScript = endBodyScript;
		this.googleMap = googleMap;
		this.address = address;
		this.facebookLink = facebookLink;
		this.googleLink = googleLink;
		this.twitterLink = twitterLink;
		this.youtubeLink = youtubeLink;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "lang", unique = true, nullable = false, length = 50)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	@Column(name = "name")
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "openHour")
	public Serializable getOpenHour() {
		return this.openHour;
	}

	public void setOpenHour(Serializable openHour) {
		this.openHour = openHour;
	}

	@Column(name = "mobile", length = 100)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "copyRight")
	public Serializable getCopyRight() {
		return this.copyRight;
	}

	public void setCopyRight(Serializable copyRight) {
		this.copyRight = copyRight;
	}

	@Column(name = "hotline", length = 100)
	public String getHotline() {
		return this.hotline;
	}

	public void setHotline(String hotline) {
		this.hotline = hotline;
	}

	@Column(name = "link", length = 200)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "headScript")
	public Serializable getHeadScript() {
		return this.headScript;
	}

	public void setHeadScript(Serializable headScript) {
		this.headScript = headScript;
	}

	@Column(name = "startBodyScript")
	public Serializable getStartBodyScript() {
		return this.startBodyScript;
	}

	public void setStartBodyScript(Serializable startBodyScript) {
		this.startBodyScript = startBodyScript;
	}

	@Column(name = "endBodyScript")
	public Serializable getEndBodyScript() {
		return this.endBodyScript;
	}

	public void setEndBodyScript(Serializable endBodyScript) {
		this.endBodyScript = endBodyScript;
	}

	@Column(name = "googleMap")
	public Serializable getGoogleMap() {
		return this.googleMap;
	}

	public void setGoogleMap(Serializable googleMap) {
		this.googleMap = googleMap;
	}

	@Column(name = "address")
	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	@Column(name = "facebookLink")
	public Serializable getFacebookLink() {
		return this.facebookLink;
	}

	public void setFacebookLink(Serializable facebookLink) {
		this.facebookLink = facebookLink;
	}

	@Column(name = "googleLink")
	public Serializable getGoogleLink() {
		return this.googleLink;
	}

	public void setGoogleLink(Serializable googleLink) {
		this.googleLink = googleLink;
	}

	@Column(name = "twitterLink")
	public Serializable getTwitterLink() {
		return this.twitterLink;
	}

	public void setTwitterLink(Serializable twitterLink) {
		this.twitterLink = twitterLink;
	}

	@Column(name = "youtubeLink")
	public Serializable getYoutubeLink() {
		return this.youtubeLink;
	}

	public void setYoutubeLink(Serializable youtubeLink) {
		this.youtubeLink = youtubeLink;
	}

	@Column(name = "isDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
